spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/relationship_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 195943884556-mv35bhkp11mej5ukctc0d2t1fr4fpu1a.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

jwt:
  expiration: 1d

password:
  encryption:
    #    key: mysecret
    key: mytestkeyasdddds

server:
  port: 2000


